### PR TITLE
Continuous (chainable) shuffle party parrot: congapartyparrot

### PR DESCRIPTION
**Pull request by hrimhari**

### CODE REVIEW

**Comment by lucymhdavies** [comment]
CPPCPPCPPCPPCPPCPPCPPCPPCPPCPPCPPCPPCPPCPPCPP

j'approve!

**Comment by Lyricalpanda** [comment]
Glasses disappear from the first parrot as it starts moving off the screen. They should stay on the first parrot

**Comment by hrimhari** [comment]
Maybe, but shufflepartyparrot was already like that.

**Comment by jmhobbs** [comment]
I'm going to merge it as is, if someone wants to make the glasses stay on this and the other one, we can do that in another PR.

Thanks!

**Pull request merged**
