### PR TITLE
Adding nyan parrot

### PR DESCRIPTION
**Pull request by vaicine**
Because Nyan Cat likes to party too!

**Example usage:**

**Peter:** Say Patrick, have you seen that new cat gif with the parrot?
**Patrick:** No I have not! Please do share.
**Peter:** Here you go:

rqgurcl

**Patrick:** nyanparrot

### CODE REVIEW

**Comment by vaicine** [comment]
Oo I didn't see someone else opened a PR for something like this already... happy to change the name?

**Comment by jmhobbs** [comment]
I like this a lot better for nyan cat.  What do you think about dropping the rainbow behind the cat/birb?   If you don't have time I can do it, but I think it could tie in the nyan cat a bit more.

**Comment by vaicine** [comment]
@jmhobbs were you thinking like this?

Flag behind: nyan-parrot-followflag

Full flag: nyan-parrot-fullflagnyan-parrot-fullflagnyan-parrot-fullflagnyan-parrot-fullflag

**Comment by jmhobbs** [comment]
OMG I love you.

I was thinking flag behind to be more like the original nyan cat, but I also like the chainable version.

Whichever you like more, submit that one.

**Comment by vaicine** [comment]
@jmhobbs while I like chainable one, flag behind is most like the original thumbsupparrot

**Pull request merged**
