### PR TITLE
Added Parrot poop

### PR DESCRIPTION
**Pull request by danrichman**
Parrot poop

### CODE REVIEW

**Comment by cavpolloosigu** [comment]
Not much of a parrot imho, it's more like a party poop :confused:

**Comment by jmhobbs** [comment]
While incredible, I agree this isn't quite a parrot.  Maybe we should have a sub-page for other `Party <noun>`, like Party Wizard, etc.
party-wizard

**Comment by cavpolloosigu** [comment]
+1 for non parrot gifs section

**Comment by danrichman** [comment]
@jmhobbs However, there is precedence in that `Nyan Parrot` is not actually a parrot. I also suspect witness protection parrot is not actually a parrot.

Besides, its parrot poop, so it has parrot DNA. 😄

**Comment by jmhobbs** [comment]
A fair assessment.  I would say we should move Nyan into a second pack as well then.  Doesn't have to be on a new page, maybe just a second section.

**Comment by jmhobbs** [comment]
Mind updating to put it in `guests.json`?  Otherwise I can merge and adjust it after.

**Comment by danrichman** [comment]
No problem @jmhobbs

**Comment by danrichman** [comment]
@jmhobbs I still think it would be funny if `witness protection parrot` may not actually be a parrot. 😄

**Comment by danrichman** [comment]
@jmhobbs I opened a new issue regarding Witness Protection Parrot and updated the `json` files.

**Comment by jmhobbs** [comment]
Rebased and rolled it all into c67e04c658efd0909813e861d9df1a0bbf90612b.

Thanks!

**Pull request closed without merging**
