### PR TITLE
Add Pepe Parrot

### PR DESCRIPTION
**Pull request by amistele**
Added Pepe the frog parrot. Should the contributors.json be updated for each pull request, or is that done by the owner?

### CODE REVIEW

**Comment by cavpolloosigu** [comment]
Some of the contributors do it. You can use [mine as an example](https://github.com/jmhobbs/cultofthepartyparrot.com/pull/180). :slightly_smiling_face: 
Also, I think the Pepe Parrot would qualify as a guest parrot. :grimacing:

**Comment by jmhobbs** [comment]
Pepe is problematic and I've chosen not to include it in the past (see #32).

Thanks for your effort, but my inclination is still to not merge this, Pepe doesn't gel with the spirit of the project to me.  Please feel free to continue discussion, I'm open to considering it but I'm currently a no.

**Comment by amistele** [comment]
@cavpolloosigu What value should "pr" in the contributors.json be set to? I couldn't find where that is referenced or what it is for.

**Comment by amistele** [comment]
@cavpolloosigu sorry if this is a stupid question, would I need to update the README.md too, or does it read the contributors.json to include everyone listed there?

**Comment by cavpolloosigu** [comment]
@amistele If I'm not wrong (which I often am), it is generated automatically by [this gulp.js script](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/ca836f2d18ee634aebd8b533c1b9a2149552b635/gulpfile.js#L22). :grin:

**Comment by matthewjwolff** [comment]
Oh look this issue is popping up again. (for reference I'm the author of the original Pepe pull request - #32 )

I don't approve of pepe's current association. But that's not exactly something we can do anything about. And even if we could a parrot project isn't the place to fix it. I'm fine with the maintainer's choice not to add pepe to the project and agree with his reasoning.

And he does kinda not fit the party parrot theme....

**Comment by jmhobbs** [comment]
Sorry I have let this PR hang open for so long, I should have addressed it sooner.

Thank you all for your civil discussion here of a charged topic.  I'm choosing, at this time, to maintain my stance of not including Pepe.

Pepe has a troubled past which his original artist Matt Furie does not approve of, and many Pepe enthusiasts do not agree with.  That does not mean however, that we can ignore how he is co-opted by other groups.  I am closing the PR because I do not believe that the negative connotations of Pepe outweigh any positive ones.  He is, in short, not someone I would want to invite to a party.

Thanks!

**Pull request closed without merging**
