### PR TITLE
Add Troll Parrot HD

### LINKED ISSUE #177: Request: Troll Parrot
Hi! 

I'm really missing the good ol :trollface: integration with our beloved `:parrot:` .... 

Whoever will implement this: I'll buy you a 🍺 !!! 😏 

Thanks! 😛  ❤️

### PR DESCRIPTION
**Pull request by mrkolby**
Troll Parrot HD

Fixes #177

### CODE REVIEW

**Comment by mrkolby** [comment]
Do you think this should be in **Party Guests** instead?

**Comment by jmhobbs** [comment]
Yeah, I would move it to Part Guests.

**Comment by mrkolby** [comment]
OK, it's done.

**Comment by jmhobbs** [comment]
Thanks!

**Comment by hvaara** [comment]
@mrkolby Do you mind if I try removing the black line that's part of Siroccos old head and change the tip to `Party officer?`? As you know, I love this repo. Fishing for contribution points 😂

**Comment by hvaara** [comment]
Or maybe just `Party?` for the tip? Seems the original trollface meme is more [known](http://knowyourmeme.com/memes/trollface-coolface-problem) as just `Problem?`, rather than `Problem officer?`.

What do you think?

**Comment by jmhobbs** [comment]
Go for it!

**Comment by mrkolby** [comment]
As I have the source files it was a quick fix. Guess @hvaara needs to fish harder ;)

**Pull request merged**
