### PR TITLE
Add Sith Parrot

### PR DESCRIPTION
**Pull request by Darth-Arminius**
HD sithparrot.gif based on the jediparrot.gif.
It has a red lightsaber and is horizontally flipped to allow sithparrot and jediparrot to duel when side-by-side.
Its colours have also been reversed with more focus on red to be more "Sith like" as well as an opposite of jediparrot.

### CODE REVIEW

**Comment by Darth-Arminius** [comment]
Just realised the creator of jediparrot was planning on creating a sithparrot. If that is still the case, I am willing to close this pull request and allow OC to add theirs.

**Comment by cavpolloosigu** [comment]
It was introduced in PR [#145](https://github.com/jmhobbs/cultofthepartyparrot.com/pull/145), on August 2017. I would safely assume OC has no short term intention to add a sith parrot. Either way, this one is cool, just tried it and it seems like a real lightsaber parrot battle. I vote for it to join the dark side of this cult :grin:

**Comment by jmhobbs** [comment]
Thanks for contributing @Darth-Arminius!  Looks great 👍

**Comment by trekroot** [comment]
@Darth-Arminius - thanks so much for doing this! The :sithparrot: is a work of art.

**Pull request merged**
