### PR TITLE
Fixed spelling for margarita parrot and blue's clues parrot

### PR DESCRIPTION
**Pull request by marcthayer**

### CODE REVIEW

**Comment by marcthayer** [comment]
Not sure what to do about the failing CI since this renames an existing parrot file.

**Comment by jmhobbs** [comment]
The gif for `bluescluesparrot.gif` needs to be renamed too, I'll override travis after that.

**Comment by marcthayer** [comment]
@jmhobbs Thanks for catching that. Pushed the [update](https://github.com/jmhobbs/cultofthepartyparrot.com/pull/77/commits/ed34f629d016972fa396663d7756ae10677a2292).

**Comment by jmhobbs** [comment]
Thanks!

**Pull request merged**
