### PR TITLE
Behold the merge parrot

### PR DESCRIPTION
**Pull request by ezbc**
and all its glory

### CODE REVIEW

**Comment by ezbc** [comment]
@jmhobbs glad to hear! Certainly I'll move it to hd. How does "merging parrot" sound?

**Comment by jmhobbs** [comment]
Merging is good, meld is another interesting word.  Fine with whatever you want to set it to when you do the hd move 😄

**Comment by ezbc** [comment]
Meld it is :+1:

**Comment by jmhobbs** [comment]
Awesome, thanks!

**Pull request merged**
