### PR TITLE
HD Conga Party Parrot

### PR DESCRIPTION
**Pull request by eokuwwy**
The file size is large, but it's HD and a lot of frames, so... :shrugparrot:

### CODE REVIEW

**Comment by eokuwwy** [comment]
CI'd :sadparrot:

**Comment by jmhobbs** [comment]
I smushed it as much as I could so it would fit 👍 
HD Conga Party Parrot
Not exactly the same, but close.

**Comment by eokuwwy** [comment]
@jmhobbs Awesome! Image has been replaced. Thank you!

**Comment by jmhobbs** [comment]
Woohoo!

**Pull request merged**
