### PR TITLE
added partygeeko to guests/hd and guests.json

### PR DESCRIPTION
**Pull request by rsimai**
As part of a hackathon event, SUSE Hackweek, we've created a guest to the party and hope it will be accepted:

https://hackweek.suse.com/18/projects/suse-incarnation-of-the-party-parrot

The image is taken from the openSUSE project. I checked with their board and received the answer

The Board haven't discussed your mail yet but speaking based on my
past experience with requests like this I think this use can be
considered parody under Fair Use doctrine and so doesn't require
explicit permission.

from their Chair, Richard Brown. We're truly fans of the parrot in SUSE and now also use the partygeeko in our internal chat, hope you will allow him to attend the party as a guest :-)

### CODE REVIEW

**Comment by rsimai** [comment]
I see the requirement now, gif needs to be 128x128 max, needs some rework ...

**Comment by cavpollo** [comment]
There is something kind of wrong with the gif :sweat_smile: 
For me, it is just a static image of all the gif frames stacked together:
image

**Comment by jmhobbs** [comment]
This is awesome!  It does appear that the gif got flattened out somewhere though.   I can grab it off the source repo if that's easier for you.

https://github.com/matthewoliver/party_geeko/blob/master/party_geeko.gif

One of the first Linux distros I used 😃

**Comment by rsimai** [comment]
Glad you like it :-)
Yes, please, go ahead, but you'll need to resize. The source indeed is Matt's repo but the preferred one is
https://github.com/matthewoliver/party_geeko/blob/master/party_geeko_border.gif
which has the black border around, same as the parrot.

**Comment by rsimai** [comment]
Don't want to appear pushy but I could close my hackweek project, once this is merged/published :-)
Seriously: is there anything missing from my side, anything I forgot?

**Comment by jmhobbs** [comment]
Hey!  Sorry, I've been AFK with a conference and vacation.  Thanks for your patience and fixing it up!

**Comment by rsimai** [comment]
Many thanks, and I've seen the cultofthepartyparrot.com page is up to date too. Please keep up the good work with that site! I'll now go and party for the rest of the week with both, parrot and geeko :-)

**Pull request merged**
