### PR TITLE
BACONATOR OR DIE!

### PR DESCRIPTION
**Pull request by jcoutch**
Added a Wendy's-themed Party Parrot.

BACONATOR OR DIE!

### CODE REVIEW

**Comment by francoislg** [comment]
Hey, where is this Hi-Res parrot!

I want this for PPaaS

**Comment by jcoutch** [comment]
@francoislg - I got the high-res/mega parrot pic from this Reddit:
https://www.reddit.com/r/PartyParrot/comments/4wkw5h/mega_parrot/?st=iz4lpisg&sh=13a77fe0

**Comment by jmhobbs** [comment]
Oh man, I didn't even notice, that's cool.  It's a shame it's not attributed anymore.

> submitted 6 months ago by [deleted]

**Comment by francoislg** [comment]
@jcoutch Still have it in transparent gif format, for my convenience? :)

**Pull request merged**
