### PR TITLE
Bootleg parrot

### PR DESCRIPTION
**Pull request by eokuwwy**
Raising awareness. There be some scammers out there.

### CODE REVIEW

**Comment by cavpolloosigu** [comment]
Gawd, what did you... what did you do to it!? D=
Hahaha xD

**Comment by jmhobbs** [comment]
fbi

**Comment by eokuwwy** [comment]
@cavpolloosigu there's at least one website selling merch that uses parrots like this. It's based on the svg file in the src directory.

**Comment by jmhobbs** [comment]
Wait, really?! That’s astounding.

**Pull request merged**
