### PR TITLE
Taco Parrot

### PR DESCRIPTION
**Pull request by deedeelavinder**
https://www.youtube.com/watch?v=kI03kC_D2ko

### CODE REVIEW

**Comment by deedeelavinder** [comment]
I think once you watch the video you will realize how much the taco_parrot is needed in the world.

**Comment by deedeelavinder** [comment]
What are your thoughts about the taco_parrot?  @jmhobbs

**Comment by jmhobbs** [comment]
It's great!  Sorry, I keep forgetting to round back to PR's on here.

**Comment by deedeelavinder** [comment]
👍  Thanks!

**Pull request merged**
