### PR TITLE
wine parrot

### PR DESCRIPTION
**Pull request by BrendanBerkley**
Wine glass was taken from http://clipart-library.com/clipart/zcXobxrMi.htm; they say "All images on our site are for Non-Commercial Use" with no mention of attribution.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Looks great!  It's failing tests because oversized though, could you adjust for that?
```
AssertionError: wineparrot.gif is wider than 128px
```

**Comment by BrendanBerkley** [comment]
I'll see what I can do.

**Comment by BrendanBerkley** [comment]
All good, I think!

**Comment by jmhobbs** [comment]
Green across the board!  Thanks for the contribution!

**Pull request merged**
