### PR TITLE
Angel Parrot

### PR DESCRIPTION
**Pull request by trcliao**
Counterpart to evil parrot.

On a side note, I got the angel wings from a site that said they were free (https://www.vecteezy.com/vector-art/154028-free-wings-collection-line-vector), so hopefully that means there won't be any copyright issues.

### CODE REVIEW

**Comment by melinerunen** [comment]
Hey! can you make based from the HD model? This is going to be a unfar fight if it's not on HD :sadparrot:

**Comment by jmhobbs** [comment]
Looks great!  +1 for an HD version, but I can merge this one and we can add HD later.

**Comment by trcliao** [comment]
Sure, I'll work on an HD version.

**Comment by trcliao** [comment]
@jmhobbs Should I add the hd angel parrot to the hd folder, get rid of the old angel parrot, and use "hd" instead of "gif" in parrots.json?

**Comment by jmhobbs** [comment]
@trcliao I would keep both versions, some people like the pixelated charm of the small ones.  HD one's go in the HD folder and then you have an entry with both fields, like so:

```
{
    "gif": "angelparrot.gif",
    "hd": "hd/angelparrot.gif",
    "name": "Angel Parrot"
}
```

Thanks!

**Pull request merged**
