### PR TITLE
Added Resonating Red Parrot for Hacktoberfest!

### PR DESCRIPTION
**Pull request by WeiJian123-tech**
Here is my parrot GIF that I created with Photpea for Hacktoberfest. I couldn't find any static jpgs or pngs for blue and green parrot so I went with red parrot which was readily available from https://cultofthepartyparrot.com as the first frame.

### CODE REVIEW

**Comment by jmhobbs** [comment]
I dig it!  But the full re-formatting of the YAML file is a bit much, can you make it so that only has your addition as the change?  Thanks!

**Comment by WeiJian123-tech** [comment]
I redownloaded the `parrots.yaml` file from your main GitHub branch and reentered Resonating Red Parrot's `.yaml` information without reformatting the entire `parrots.yaml` file.  Sorry about that. I thought I had to deploy as a step before contributing so I npm installed `cultofthepartyparrot`. It might have been me running npm that changed `parrots.yaml` file's format but I am not entirely sure. 

image

Is this a good fix even though my check now fail?

**Comment by jmhobbs** [comment]
Hey @WeiJian123-tech, no worries, I'm not sure what went wrong there.  I hope you don't mind, I cleaned up the conflicts so that this would deploy and we could merge it.

Thanks for adding this parrot!

**Comment by WeiJian123-tech** [comment]
That is quite alright. I really don't mind. It was fun creating and contributing a cultoftheparrot.com parrot `.gif`.  😄

**Pull request merged**
