### PR TITLE
FIX sync shuffle parrots

### PR DESCRIPTION
**Pull request by viktorsec**
Tunes Shuffle Parrot and Shuffle Further Parrot to sync better in Slack.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Not sure this needs fixing.  The two weren't necessarily meant to be chained, and `:congalineparrot:` does a good job of that already.

I'm open to discussion on this though.

**Comment by viktorsec** [comment]
I find something wonderful in summoning a chain of gracefully aligning alternating Shuffle Parrots and Shuffle Further Parrots. Anyway, of course, it's up to you!

Parrot Shuffle Conga

**Comment by viktorsec** [comment]
@jmhobbs This PR is open for over half a year now. Feel free to reject it, I won't be disappointed!

:)

**Comment by jmhobbs** [comment]
Sorry!  I let this one fall through the cracks.  I dig the chaining 💯

**Pull request merged**
