### PR TITLE
add new matrix parrot

### LINKED ISSUE #417: Matrix Parrot HD
Full size (128x128): matrix
Reduced size to meet Slack 128Kb file restrictions (64x64): matrix_small

### PR DESCRIPTION
**Pull request by TimGoldbach**
Resolves #417

### CODE REVIEW

**Review by jmhobbs — CHANGES_REQUESTED** [review]
Love it!  Could you move it to `parrots/hd/` and update the YAML accordingly?

**Comment by jmhobbs** [comment]
Hmmm, on second thought, maybe not?  This is 64x64 and HD are (all?) 128x128.  Tricky, since the image looks so good.

**Review by jmhobbs — APPROVED** [review]

**Comment by TimGoldbach** [comment]
@jmhobbs I also have the 128x128 version of this, but it is too big, since it is 218kb big.

**Comment by jmhobbs** [comment]
Makes sense 👍 

Maybe we need a `4k` gif option 😉 

Thanks again!

**Pull request merged**
