### PR TITLE
Added Turn Down for Watch Parrot

### PR DESCRIPTION
**Pull request by xMcLOVINx**

### CODE REVIEW

**Review by jmhobbs — CHANGES_REQUESTED** [review]
The gif is too large for the default folder, can you move it to `parrots/hd/`?  Additionally you'll need to update the `gif: turndownforwatchparrot.gif` key in the YAML to `hd: hd/turndownforwatchparrot.gif`

Thanks!

**Comment by xMcLOVINx** [comment]
How can I move this file?

**Comment by jmhobbs** [comment]
No worries, I can move it 👍

**Comment by jmhobbs** [comment]
Bah, now it's a size issue.  I'll see what I can do.  It needs to be < 128px in both height and width, and <128kb in size.

**Comment by xMcLOVINx** [comment]
Ty ^^

**Review by jmhobbs — APPROVED** [review]

**Comment by xMcLOVINx** [comment]
Can you add the "hacktoberfest-accepted" label, or approve my pull request to be used in hacktoberfest?

**Comment by jmhobbs** [comment]
Shouldn't be needed since the project has the tag, but I'll give it a shot.

**Pull request merged**
