### PR TITLE
Adds Everything's Fine (flaming), Metal (headbanging), & TP (hoarding)

### PR DESCRIPTION
**Pull request by danryder**
some HD parrots

please note: the flames in "everything's fine", the hair from "metal" and the mountain of TP are all snagged from google image search results. I didn't see any copyright notifications let alone crop any out.

### CODE REVIEW

**Comment by jmhobbs** [comment]
I'd like to bring in the metal parrot from #449 too, what do you think about renaming your metal parrot?  Maybe headbanging parrot? (forgive my lack of metal knowledge if that is the wrong term)

**Comment by danryder** [comment]
I didn't actually see his parrot yet (the image) but you can call it whatever you like!

headbangingparrot is fine

I'm also not an expert but there are also lots of types of metal - to name a few "Thrash metal", "Nu metal", "Deth metal", "Black metal", "Groove Metal"... so thrashmetalparrot, numetalparrot, dethmetalparrot, hairmetalparrot, moshparrot, moshpitparrot, parrotalliica (parrotica sounds like something that might interest the original Sirocco...)

whatever works for you!

**Comment by danryder** [comment]
@jmhobbs confession - I haven't been adding these to parrots.yaml 😬

**Comment by jmhobbs** [comment]
Done, thanks!

**Pull request merged**
