### PR TITLE
Four new parrtots: Birthday, Jedi, Invisible, Angry

### PR DESCRIPTION
**Pull request by trekroot**
hd-Birthday, hd-Jedi, Invisible, Angry Parrot additions

### CODE REVIEW

**Comment by jmhobbs** [comment]
I mean, invisible parrot is clever I guess, but I'm not sure it needs to go in.

Also, it would be cool to have a sith parrot facing right so they could duel.

**Comment by trekroot** [comment]
Will do - I can remove invisible parrot. I'll get sithparrot set this weekend.

**Comment by natelowry** [comment]
Invisible parrot needs to stay in 🤣

**Comment by dnguyenchevy** [comment]
Could you make invisible parrot have like a John Cena theme?

**Comment by jmhobbs** [comment]
I'm on the invisible parrot train now, going to merge 😄   Sith can come later if someone has time.

Thanks for your contribution!

**Pull request merged**
