### PR TITLE
Added Portal Parrot (Orange Portal) and Portal Parrot (Blue Portal)

### PR DESCRIPTION
**Pull request by jesivasq**
The parrot goes into the orange portal and then pops out of the blue one

### CODE REVIEW

**Comment by jmhobbs** [comment]
These are great!  How should these play in with #203?  Think it should replace it?

**Comment by cavpolloosigu** [comment]
I would vote to keep both :grin:

**Comment by jesivasq** [comment]
Thank you heaps! I vote to keep both, too.

**Comment by jmhobbs** [comment]
Thanks @jesivasq!

**Comment by jesivasq** [comment]
Thanks @jmhobbs!

**Pull request merged**
