### PR TITLE
Adding grumpy parrot

### PR DESCRIPTION
**Pull request by lurch83**
Want to party? No

### CODE REVIEW

**Comment by threehams** [comment]
grumpy parrot looks too energetic.

**Comment by yqzhang** [comment]
How did you make this one? What tool did you use to animate the grumpy cat?

**Comment by AtlasRider** [comment]
I think mixing other characters takes away from Party Parrot's individuality. Not a fan of this one.

**Comment by dnguyenchevy** [comment]
When I think of grump parrot, I would imagine a non-moving parrot with  strobing colour changing affects with some "grumpy cat" features and not completely photoshopped face.

**Comment by jmhobbs** [comment]
Closing for now.  Grumpy Cat [has been litigious in the past](http://venturebeat.com/2016/08/30/grumpy-cat-suing-coffee-maker-for-1-8-million-over-grumppuccinno-copyright-violations/) and this one is just meh for me in any case.

**Comment by yqzhang** [comment]
@lurch83 Just a quick question. What software did you use to create this GIF? Thank you!

**Comment by lurch83** [comment]
@yqzhang just photoshop. Can split the gif frame by frame.

There is also Party Parrot as a Service. https://parrotify.github.io/  (I am not affiliated with that site)

**Comment by yqzhang** [comment]
@lurch83 Gotcha. Thanks man!

**Pull request closed without merging**
