### PR TITLE
add masked parrot

### PR DESCRIPTION
**Pull request by naturald**
Corona is taking even the parrots.
but luckily the masks exist and as a men said: "safety is number one priority".

BTW good Hacktoberfest everyone.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Thanks!  I really thought we had one of these, but I guess not!

Vaccine parrot approves of masking!

**Comment by jmhobbs** [comment]
Oh!  Could you move it to the `hd/` directory and update the YAML to `hd/maskparrot.gif`?

Thanks!

**Comment by naturald** [comment]
ok i have done it.

**Comment by jmhobbs** [comment]
Perfect, thanks!

**Pull request merged**
