### PR TITLE
Let's get this Love Parrot partying!!!

### PR DESCRIPTION
**Pull request by deedeelavinder**
The party parrots play an everyday role in my life.  I need the :loveparrot: asap!!

Thank you!!

loveparrot copy

### CODE REVIEW

**Comment by jmhobbs** [comment]
Nice!  Any reason why you used right parrot instead of the other as your base?

**Comment by deedeelavinder** [comment]
I liked the heart on the left.  Could go either way, I guess.

**Comment by jmhobbs** [comment]
Works for me 😄

**Comment by deedeelavinder** [comment]
@jmhobbs Any chance this can be merged today?  
image

**Comment by jmhobbs** [comment]
Whoops!  Done!  Good day for it too 😄

**Pull request merged**
