### PR TITLE
Biker Parrot

### PR DESCRIPTION
**Pull request by eokuwwy**
I'm open to suggestions if you hate this

### CODE REVIEW

**Comment by eokuwwy** [comment]
Bump. It's not so bad, is it?

**Comment by cavpolloosigu** [comment]
Sorry, it's bad... badass! xP
Tho, can it have a bandana and a tattoo? Or will it be lost inside it all =\

**Comment by jmhobbs** [comment]
Ha! It's not bad, I'm just a slow reviewer.

**Comment by eokuwwy** [comment]
I’ll give the bandana a shot. 😎

**Comment by eokuwwy** [comment]
bikerparrot

**Comment by jmhobbs** [comment]
🙌

**Pull request merged**
