### PR TITLE
Adding Unit test for File size!!!

### PR DESCRIPTION
**Pull request by melinerunen**
The parrots need to be checked since slack requires parrots with 64kb or less

### CODE REVIEW

**Comment by melinerunen** [comment]
The travis is saying that convet-units is missing but I'm adding it in the package.json with my commit.

**Comment by jmhobbs** [comment]
+1 for separation!  We can probably drop the convert-units and replace with a constant TBH, I'll poke at travis though.

**Comment by jmhobbs** [comment]
I don't run a full npm install in travis because we don't need all the packages.  Can you update `.travis.yml` and add `convert-units` on line 4?

**Comment by melinerunen** [comment]
Initially I was with the constant aproach but I thoungh that it will be more elegant using a module instead of a constant. 
It's your call  :D

**Comment by jmhobbs** [comment]
Nah, looks great.  Thanks!

**Pull request merged**
