### PR TITLE
Add schnitzel parrot

### PR DESCRIPTION
**Pull request by christianrank**

### CODE REVIEW

**Comment by mrkolby** [comment]
Do you have the schnitzel in HD so you could do an HD version?

**Comment by jmhobbs** [comment]
Merged a different file and messed up `parrots.json`, do you mind updating?  Thanks!

**Comment by christianrank** [comment]
@mrkolby I tried, but couldn't get the gif below 64KB in HD. (The parrot does 7 rotations.)

@jmhobbs done 🙂

**Comment by jmhobbs** [comment]
@christianrank mind sharing the HD version?  Maybe we can find a way to squish it down enough with `giflossy` or something.

**Comment by christianrank** [comment]
Sure, good luck! 🙂

**Comment by jmhobbs** [comment]
Yeah, that's a tough one.  Only option I think would be to turn the Schnitzel into flat art instead of a photo.  I'll merge this and then open a ticket to come back to that.

**Comment by christianrank** [comment]
@jmhobbs what about merging?

I'm coming back here every few months to resolve conflicts again.

**Comment by jmhobbs** [comment]
Whoops! Left it to linger, sorry! Thanks for fixing the conflicts!

**Pull request merged**
