### PR TITLE
Add Poke Parrot

### PR DESCRIPTION
**Pull request by kyourikey**
Nice to meet you, let's add new members to Party Parrot! Thank you.
pokeparrot

### CODE REVIEW

**Comment by jmhobbs** [comment]
Such balance!  Does it make sense to add the button on there?  Right now this looks like the back of the Poke ball.  I can merge it for now and we can add it later too, if that'd be preferred.

**Comment by kyourikey** [comment]
I will change to the front design!
Please wait a moment. 😃

**Comment by kyourikey** [comment]
I'm done, the front version!
Thank you.

pokeparrot

**Comment by jmhobbs** [comment]
That looks incredible!  Thank you so much!

**Comment by kyourikey** [comment]
Thank you very much. 🦜

**Pull request merged**
