### PR TITLE
partypenguin.gif - because Linux loves parrots too

### PR DESCRIPTION
**Pull request by nathanchere**

### CODE REVIEW

**Comment by westerlund** [comment]
that's no parrot :((((((

**Comment by nathanchere** [comment]
The people have spoke!

**Comment by jmhobbs** [comment]
Sorry @nathanchere!

I ❤️ tux but ¯\\\_(シ)_/¯

**Comment by jmhobbs** [comment]
We now have a `Party Guests` section, #167.  This might fit there if anyone wants to open a fresh PR.

**Pull request closed without merging**
