### PR TITLE
Added Rythmical Parrot

### PR DESCRIPTION
**Pull request by akihanari**
Because I wanted to see him enjoying the party.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Oh shoot, looks like it needs a rebase.  LMK if you'd like me to fix that, otherwise ping me and I'll merge up once it's ready.  Thank you!

**Comment by akihanari** [comment]
Resolved a json file conflict.
LMK if you have anything else to do! (I'm sorry if you couldn't do your intention.)

**Comment by akihanari** [comment]
> thumbs_up_parrot
> 
> 大好きです。JSONの中括弧を修正する必要があります。

**Comment by akihanari** [comment]
@eokuwwy Thank you! Corrected the relevant section.

**Comment by jmhobbs** [comment]
Awesome! Thanks for patching it up, top notch parrot 💯

**Pull request merged**
