### PR TITLE
owls need to party too

### PR DESCRIPTION
**Pull request by hrousley**
Owl head sourced from here: http://emojipedia.org/owl/ 

bonus for twin peaks fans

### CODE REVIEW

**Comment by jmhobbs** [comment]
Now that we have #169, maybe this fits in there?

**Comment by hrousley** [comment]
@jmhobbs Should I resolve the merge conflict for ya?

**Comment by jmhobbs** [comment]
If you'd like, or I can.  I wanted to make sure you'd be ok with moving it to the Guests section.  Thanks!

**Comment by hrousley** [comment]
If it's faster/easier for you, I don't mind. Moving to Guests is a-okay with me!

**Comment by jmhobbs** [comment]
Merged in 9e5cd6b9458854dedb5266cce90ca201fdcc7fd7 and 6ad91ddcafe9020f0e2cb778aa18fddc60af31a5.

Thanks!

**Pull request closed without merging**
