### PR TITLE
Add hd/Disco, Matrix, Papal, Stalker Parrots and update parrots.json

### PR DESCRIPTION
**Pull request by trekroot**

### CODE REVIEW

**Comment by bhamilton-idexx** [comment]
I know this person, and I firmly believe that they are the party parrot personified.

**Comment by dnguyenchevy** [comment]
These are fantastic. 💯

**Comment by jmhobbs** [comment]
Thanks!

**Comment by trekroot** [comment]
Thank you. And never been more pleased to contribute than to the cult!

-trekroot

**Pull request merged**
