### PR TITLE
Added link for parrot.today website.

### PR DESCRIPTION
**Pull request by oibind**
parrot.today is a website that displays a new random parrot every single
day.

### CODE REVIEW

**Comment by jmhobbs** [comment]
That's a great idea!  I'm seeing this there right now though; 
Screen Shot 2019-03-18 at 10 22 06 AM

**Comment by oibind** [comment]
I'm using a dataset from ImageNet for a source of images at the minute. Sometimes the URLs they have aren't live anymore. The link the python script chose at random from the list provided today just isn't live anymore. I've updated it to show a working example. 

image

**Comment by jmhobbs** [comment]
Right on!

**Comment by oibind** [comment]
Drat didn't think but can I be added to the thanks section of the README? :heart_eyes:

**Comment by jmhobbs** [comment]
Absolutely!  I've got a lot of catch up work to do on there anyway 😸

**Comment by oibind** [comment]
Delete this branch already, so I'll have to send it in another pull request.

**Pull request merged**
