### PR TITLE
Add British Parrot

### PR DESCRIPTION
**Pull request by sashforth**
There aren't any other flag parrots (except the Pride Parrot), so I wasn't sure if there were rules against these.

### CODE REVIEW

**Comment by Darth-Arminius** [comment]
I like it, in time for it coming home and all.

**Comment by jmhobbs** [comment]
I'm for it!  There is http://countryparrots.com/ but this is much fancier.

Can I beg a rebase from you?  Thanks!

**Comment by sashforth** [comment]
Rebased :)

**Comment by jmhobbs** [comment]
Thanks!

**Pull request merged**
