### PR TITLE
Created transparent parrot

### PR DESCRIPTION
**Pull request by smlevorse**
Transparency is a valued trait. Whether in slackmoji, or in organizations, transparency should be celebrated.

### CODE REVIEW

**Comment by jmhobbs** [comment]
fry

**Comment by smlevorse** [comment]
Is that a no?

**Comment by jmhobbs** [comment]
It’s an “I’m not sure.”

It’s funny for sure, but I’m not sure of the value of adding it. 

There seems to be support for it, so leaning towards yes.

**Comment by smlevorse** [comment]
If it helps explain the value, the slack org I'm a part of strongly encourages emoji to have transparent backgrounds so that when you hover over them, you don't see a white square. So I made this so we can celebrate when people fix their not so transparent mistakes. Though, it is also useful when higher ups explain why they make the choices they make.

**Comment by jmhobbs** [comment]
Works for me! 👍

**Pull request merged**
