### PR TITLE
Proposed Hanukkah parrot.

### PR DESCRIPTION
**Pull request by jmhobbs**
Here's a proposed Hanukkah parrot with a dreidel to #59 

Feedback please!

### CODE REVIEW

**Comment by jmhobbs** [comment]
Here's a version with a white border on the dreidel.

driedelparrot2

**Comment by jmhobbs** [comment]
Larger!

dreidel-parrot

**Comment by edwardsfriedman** [comment]
I like the the Larger one!

**Comment by kbvincent** [comment]
Love it, looks like he is spinning it with his beak!

**Comment by jmhobbs** [comment]
Larger one it will be, thanks!

**Comment by edwardsfriedman** [comment]
🙏  thanks a bunch!

**Pull request merged**
