### PR TITLE
Emoji that you can chain together in Slack

### PR DESCRIPTION
**Pull request by ifreecarve**
This pull request speaks for itself.

shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2shuffle1shuffle2

### CODE REVIEW

**Comment by jmhobbs** [comment]
`shuffleparrot` and `shufflefurtherparrot` used to work that way.  Instead of `shuffleparrot2`, want to just override `shufflefurtherparrot`?

I've always thought `shufflefurtherparrot` was too fast anyway.

**Comment by ifreecarve** [comment]
That was actually my first thought, but then I noticed that `shufflefurtherparrot` does indeed shuffle a few pixels faster in the middle.

**Comment by jmhobbs** [comment]
Yeah, that's just my lack of gif editing ability.  I'm all for replacing that one.  It's pretty much _only_ used when chained with the first one.

**Comment by ifreecarve** [comment]
Note that I've fixed it as per your comments -- I squashed the old commit by `push -f`

**Comment by jmhobbs** [comment]
Hah!  Tricky tricky :)

Thanks!

**Pull request merged**
