### PR TITLE
Added smug parrot

### PR DESCRIPTION
**Pull request by matthewjwolff**
Hey guys.

I made a pepe parrot and wanted to share it upstream. I'm open to suggestions if there are any. 
smugparrot

REEEEEEEEEEEEEEE

### CODE REVIEW

**Comment by dnguyenchevy** [comment]
pepe is that you?

**Comment by jmhobbs** [comment]
That makes me incredibly uncomfortable.

**Comment by matthewjwolff** [comment]
Ok I just rebased so this branch should have no more conflicts

**Comment by heinst** [comment]
Please shrink this to 64Kb so that way it is easily importable to Slack

**Comment by ctcpip** [comment]
slack has max dimensions of 128px.  can you please accommodate? thanks and praise

**Comment by jmhobbs** [comment]
Given pepe's current....situation, I'm going to pass on this one.  Plus he's creepy AF in parrot form.

**Pull request closed without merging**
