### PR TITLE
Add Sushi parrot 🍣

### PR DESCRIPTION
**Pull request by belltailjp**
I'm glad if the cult would love to have Sushi parrot!
sushiparrot
It's based on parrot HD, and sushi image is captured from OS X 🍣 character, so no concern about licensing.

### CODE REVIEW

**Comment by jmhobbs** [comment]
🤔   Why is it on the head?  Why not eating it?

**Comment by belltailjp** [comment]
I intended to make something similar to pizza, banana or icecream parrots (they aren't actually eating) but if you'd prefer I can modify it, like the hamburger parrot!!

**Comment by cavpolloosigu** [comment]
Why not both!? =D

**Comment by jmhobbs** [comment]
Fair enough, just thought it was odd having it at hat level, but if that's the intent, I'm cool with it 👍

**Comment by jmhobbs** [comment]
Thanks for your contribution!

**Comment by olsonm16** [comment]
It’s like he’s bringing you a sushi roll. What a selfless sushi parrot! Love it!

**Pull request merged**
