### PR TITLE
add trump parrot

### PR DESCRIPTION
**Pull request by askkaz**
trumpparrot

### CODE REVIEW

**Comment by jmhobbs** [comment]
Thanks for contributing, but I'll have to decline this one.

**Comment by threehams** [comment]
This is the third Trump parrot request in a month. You might want to post an executive order on the README.

**Comment by oneiroislives** [comment]
Is it wise to pretend like this person doesn't exist, or are you just trying to avoid political/controversial figures all together?  Would you approve a Mueller parrot?

**Comment by jmhobbs** [comment]
Generally speaking, any obviously controversial figures are probably going to be a pass.  I would not accept a Mueller or Hillary for the same general reasons.  So far we've avoided "real people" all together for the most part.  The obvious exceptions that come to mind are Ryan Gosling, Nicholas Cage and Guy Fieri.  But these three are established internet jokes and generally in-offensive otherwise.

**Pull request closed without merging**
