### PR TITLE
Added Thumbs Up Parrot

### PR DESCRIPTION
**Pull request by zeftilldeath**
An essential new parrot.

### CODE REVIEW

**Comment by bharley** [comment]
The parrot's hands are backwards.

**Comment by jmhobbs** [comment]
Maybe he's holding his arm across his body.  I think it'd look weird if the thumb was on the outside.

**Comment by daveyarwood** [comment]
👍  for 👍  parrot

**Comment by threehams** [comment]
Already using this on Slack. <-- early adopter

**Comment by augbog** [comment]
I'm really excited for this parrot! Hopefully merge conflicts get fixed soon :)

**Comment by jmhobbs** [comment]
Skipped the rebase craziness and just pulled it in externally.  Thanks @zeftilldeath!

**Pull request closed without merging**
