### PR TITLE
Add three new parrots to the mix

### PR DESCRIPTION
**Pull request by andyhmltn**
This pull request adds three new parrots:

* Conga Party Parrot
* Chill Parrot

And my personal favourite:

* Explody Parrot

### CODE REVIEW

**Comment by JacopoGobbi** [comment]
congapartyparrot is not coming from conga, is it? Since on slack they aren't properly synchronized... 
Anyway amazing work

**Comment by andyhmltn** [comment]
Ah yeah, that's my bad.  We have a different parrot conga on our slack 😄 Thanks, glad I could help!

**Comment by jmhobbs** [comment]
These are cool!  If you can rename conga parrot to something else I'll merge this for sure.
My only problem with having conga in the name is that conga parrot is an established style.

**Comment by andyhmltn** [comment]
Absolutely 😄 All done @jmhobbs

**Pull request merged**
