### PR TITLE
Added the Groke Parrot gif

### PR DESCRIPTION
**Pull request by rkruk**
I just added thegrokeparrot.gif - as The Groke character from the Moomin stories created by Tove Jansson.

[x] - Add your parrot gif to parrots/ and append an entry to parrots.json.
[x] - Make sure the parrot gif file is named [name]parrot.gif in all lower case e.g. exampleparrot.gif.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Love it, just two things.  Looks like the JSON got a little wonky, and I think this would actually go better in the guests than in the parrots.

Thanks!

**Comment by rkruk** [comment]
Hi there!
I fixed that wonky JSON of mine (I hope it is better now), and moved thegrokeparrot.gif to guests folder.
Sorry for such crooked commit.

**Comment by richrd** [comment]
Hehe, fun to see my parrot in a PR :smile: This is likely taken from http://www.slackmojis.com/emojis/6303-thegrokeparrot 
Unfortunately there are conflicts, any chance of a rebase & merge?

**Comment by jmhobbs** [comment]
Awesome @richrd, glad you're on board 😅 

Sorry I let this one slip after you updated @rkruk, I can handle fixing this one up.

**Comment by jmhobbs** [comment]
Got it in [here](https://github.com/jmhobbs/cultofthepartyparrot.com/commit/497cefcf109e060bb354e5e07baf6dc34de2086b) and it is live 👍 

Thanks y'all!

**Pull request closed without merging**
