### PR TITLE
calvinist_parrot

### PR DESCRIPTION
**Pull request by Jegama**
If we have a papal parrot, we need a reformed parrot.

### CODE REVIEW

**Comment by cavpolloosigu** [comment]
Just a curious question. Any reason why the parrot/gif doesn't loop? :no_mouth:

**Comment by jmhobbs** [comment]
I'll need 95 reasons to merge this ;)

Can you make it loop though?  Then we should be good to merge.

Thanks!

**Comment by jmhobbs** [comment]
I usually use [gimp](https://www.gimp.org/) and [gifsicle](https://www.lcdf.org/gifsicle/)  I'll make it loop and attach it to this thread so you can drop it into your PR.

**Comment by jmhobbs** [comment]
There!  You can use this if you like.

calvinist_parrot

**Comment by Jegama** [comment]
Thanks! I just added the one that you shared.

**Comment by jmhobbs** [comment]
Awesome, thanks for sharing!

**Pull request merged**
