### PR TITLE
uploading some new quarantine / work-from-home parrots I made

### PR DESCRIPTION
**Pull request by danryder**
the house was snagged from a google-image search

### CODE REVIEW

**Comment by danryder** [comment]
no, this is not (as someone on reddit asked when I posted this there) the house from Blues Clues :-D

**Comment by danryder** [comment]
I didn't modify any JSON files and these can probably go in "HD" folder - they are all 128x128

**Comment by jmhobbs** [comment]
These are great!  I wonder if we should move these and the other ones into a "social isolation" group on the page. 🤔

**Comment by danryder** [comment]
Wait I forgot one of my co-workers made a "mask parrot" which I will try and submit as well lol

**Comment by danryder** [comment]
@jmhobbs confession - it looks like I didn't add these to parrots.yaml 😬

**Pull request merged**
